/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  devv4GuideSidebar: [
    "dev-guide/v4/index",
    "dev-guide/v4/foreword",
    {
      type: "doc",
      label: "Quick Start",
      id: "dev-guide/v4/getting-started",
    },
    {
      type: "category",
      label: "Flared Basics",
      items: [
        "dev-guide/v4/intro/introduction",
        "dev-guide/v4/intro/how-to-read",
        "dev-guide/v4/intro/buttplug-ethics",
        "dev-guide/v4/intro/getting-help",
      ],
    },
    {
      type: "category",
      label: "Strategies Against Buttplug Architecture",
      items: [
        "dev-guide/v4/architecture/intro",
        "dev-guide/v4/architecture/sessions-and-components",
        "dev-guide/v4/architecture/protocol-in-depth",
        "dev-guide/v4/architecture/client-in-depth",
        "dev-guide/v4/architecture/client-device-in-depth",
        "dev-guide/v4/architecture/server-in-depth",
        "dev-guide/v4/architecture/intiface",
        "dev-guide/v4/architecture/terms",
      ],
    },
    {
      type: "category",
      label: "Sticking Buttplug In",
      items: [
        "dev-guide/v4/writing-buttplug-applications/intro",
        "dev-guide/v4/writing-buttplug-applications/api-basics",
        "dev-guide/v4/writing-buttplug-applications/connectors",
        "dev-guide/v4/writing-buttplug-applications/connecting",
        "dev-guide/v4/writing-buttplug-applications/device-enum",
        "dev-guide/v4/writing-buttplug-applications/device-info",
        "dev-guide/v4/writing-buttplug-applications/device-control",
        "dev-guide/v4/writing-buttplug-applications/application",
        "dev-guide/v4/writing-buttplug-applications/logging",
      ],
    },
    {
      type: "category",
      label: "Winning Ways for Your Buttplug Plays",
      items: [
        "dev-guide/v4/cookbook/intro",
        {
          type: "category",
          label: "Buttplug Connectors, Connections, and Engines",
          items: [
            "dev-guide/v4/cookbook/connections/embedding",
            "dev-guide/v4/cookbook/connections/ping",
          ],
        },
        {
          type: "category",
          label: "Devices and Commands",
          items: [
            "dev-guide/v4/cookbook/devices-and-commands/intro",
            "dev-guide/v4/cookbook/devices-and-commands/device-configurations",
          ],
        },
        {
          type: "category",
          label: "Integrating Buttplug in Games",
          items: [
            "dev-guide/v4/cookbook/games/intro",
            "dev-guide/v4/cookbook/games/unity",
            "dev-guide/v4/cookbook/games/unreal",
            "dev-guide/v4/cookbook/games/modding",
          ],
        },
        "dev-guide/v4/cookbook/privacy-models",
      ],
    },
    {
      type: "category",
      label: "Implementing new Devices and Clients",
      items: [
        "dev-guide/v4/inflating-buttplug/intro",
        {
          type: "category",
          label: "Adding and Customizing Devices",
          items: [
            "dev-guide/v4/inflating-buttplug/devices/intro",
            "dev-guide/v4/inflating-buttplug/devices/device-configuration-file",
            "dev-guide/v4/inflating-buttplug/devices/websocket-device-manager",
            "dev-guide/v4/inflating-buttplug/devices/adding-device-protocols",
            "dev-guide/v4/inflating-buttplug/devices/adding-device-comm-managers",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Appendices",
      items: ["dev-guide/v4/appendices/history-of-buttplug"],
    },
  ],
  specSidebar: [
    "spec/v4/index",
    "spec/v4/changelog",
    "spec/v4/architecture",
    "spec/v4/messages",
    "spec/v4/status",
    "spec/v4/identification",
    "spec/v4/device_discovery",
    "spec/v4/device_information",
    "spec/v4/stop",
    "spec/v4/output",
    "spec/v4/input",
    "spec/v4/deprecated",
  ],
  stpihkalSidebar: [
    "stpihkal/index",
    {
      type: "category",
      label: "Protocols and Memory Layouts",
      items: [
        {
          type: "autogenerated",
          dirName: "stpihkal/protocols",
        },
      ],
    },
    {
      type: "category",
      label: "Firmware and Bootloaders",
      items: [
        {
          type: "autogenerated",
          dirName: "stpihkal/firmware",
        },
      ],
    },
    {
      type: "category",
      label: "Network Protocols",
      items: [
        {
          type: "autogenerated",
          dirName: "stpihkal/network",
        },
      ],
    },
    {
      type: "category",
      label: "Video Encoding Formats",
      items: [
        {
          type: "autogenerated",
          dirName: "stpihkal/video-encoding-formats",
        },
      ],
    },
  ],
};

module.exports = sidebars;
