/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  devGuideSidebar: [
    'dev-guide/index',
    'dev-guide/foreword',
    {
      type: 'category',
      label: 'Introduction',
      items: ['dev-guide/intro/introduction', 
      'dev-guide/intro/how-to-read', 
      'dev-guide/intro/buttplug-ethics', 
      'dev-guide/intro/getting-help'],
    },
    {
      type: 'category',
      label: 'Strategies Against Buttplug Architecture',
      items: ['dev-guide/architecture/intro', 
      'dev-guide/architecture/sessions-and-components', 
      'dev-guide/architecture/protocol-in-depth', 
      'dev-guide/architecture/client-in-depth', 
      'dev-guide/architecture/server-in-depth', 
      'dev-guide/architecture/terms'],
    },
    {
      type: 'category',
      label: 'Sticking Buttplug In',
      items: ['dev-guide/writing-buttplug-applications/intro', 
      'dev-guide/writing-buttplug-applications/api-basics',
      'dev-guide/writing-buttplug-applications/connectors', 
      'dev-guide/writing-buttplug-applications/connecting',
      'dev-guide/writing-buttplug-applications/device-enum',
      'dev-guide/writing-buttplug-applications/device-control',
      'dev-guide/writing-buttplug-applications/application',
      'dev-guide/writing-buttplug-applications/logging',
    ]
    },
    {
      type: 'category',
      label: 'Winning Ways For Your Buttplug Plays',
      items: ['dev-guide/cookbook/intro', 
      'dev-guide/cookbook/connector-setup-in-depth',
      'dev-guide/cookbook/privacy-models', 
      'dev-guide/cookbook/raw-device-commands'],
    },
    {
      type: 'category',
      label: 'Inflating Buttplug',
      items: ['dev-guide/inflating-buttplug/intro'],
    },
  ],
  specSidebar: [
    'spec/index',
    'spec/changelog',
    'spec/architecture',
    'spec/messages',
    'spec/status',
    'spec/identification',
    'spec/enumeration',
    'spec/generic',
    'spec/sensors',
    'spec/raw',
    'spec/deprecated'
  ],
  stpihkalSidebar: [
    'stpihkal/index',
    {
      type: 'category',
      label: 'Protocols and Memory Layouts',
      items: [{
        type: 'autogenerated',
        dirName: 'stpihkal/protocols'
      }]
    },
    {
      type: 'category',
      label: 'Firmware and Bootloaders',
      items: [{
        type: 'autogenerated',
        dirName: 'stpihkal/firmware'
      }]
    },
    {
      type: 'category',
      label: 'Network Protocols',
      items: [{
        type: 'autogenerated',
        dirName: 'stpihkal/network'
      }]
    },
    {
      type: 'category',
      label: 'Video Encoding Formats',
      items: [{
        type: 'autogenerated',
        dirName: 'stpihkal/video-encoding-formats'
      }]
    },
  ],
};

module.exports = sidebars;
